### ISSUE TITLE
[Question] Is catalog schema in the proper directory?

### ISSUE THREAD

**Issue by leecalcote** [meshery/schemas#101]
### Current Behavior
From the perspective of the layout and organization of this repo, is [this](https://github.com/meshery/schemas/tree/master/models/v1alpha2) where it belongs?

### Desired Behavior
Ideally, there is a description of the organization of this repo by top-level folder in the README.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by MUzairS15** [comment]
Catalog schema is present at https://github.com/meshery/schemas/blob/master/schemas/constructs/v1alpha1/catalog_data.json

**Comment by MUzairS15** [comment]
Yes the description needs to be added. 👍🏻
