### ISSUE TITLE
[Schemas] Import Design: remove checklist for type

### ISSUE THREAD

**Issue by leecalcote** [meshery/schemas#39]
@Yashsharma1911 will you remove the checkboxes from this selection?

<img width="604" alt="Screenshot 2023-12-20 at 1 45 02 PM" src="https://github.com/meshery/meshery/assets/7570704/51f45a6f-7533-4095-883b-586673bae514">

[Slack Message](https://layer5io.slack.com/archives/C023QGMSH8D/p1703101529070429)

**Comment by Yashsharma1911** [comment]
This issue is resolved
